
(* TODO:
 * - finish wrapper functions around simplex
*)

open Expr
open Node
open Mlproof
module S = Simplex.Make(struct type t = Expr.t let compare = Expr.compare end)

let get_type = function
    | Etrue | Efalse -> "$o"
    | Etau (_, t, _, _) -> t
    | e -> begin match priv_type e with
        | None -> Namespace.univ_name
        | Some s -> s
    end

let is_int e = get_type e = "$int"
let is_rat e = get_type e = "$rat"

(* Manipulation of expressions/formulas *)
exception NotaFormula

let is_z v = Z.equal (Q.den v) Z.one
let is_q v = not (Z.equal (Q.den v) Z.zero || is_z v)
let floor v =
    try
         Q.of_bigint (Z.ediv (Q.num v) (Q.den v))
    with Division_by_zero -> v
let ceil v = Q.neg (floor (Q.neg v))

let comp_neg = function
    | "$less" -> "$greatereq"
    | "$lesseq" -> "$greater"
    | "$greater" -> "$lesseq"
    | "$greatereq" -> "$less"
    | _ -> assert false

let ctype t t' = match t, t' with
    | "$int", "$int" -> "$int"
    | "$int", "$rat" | "$rat", "$int" | "$rat", "$rat" -> "$rat"
    | _ -> "$real"
let etype e e' = ctype (get_type e) (get_type e')

let mk_app t s l = add_type t (eapp (s, l))

let const s =
    if is_z (Q.of_string s) then
        mk_app "$int" s []
    else
        mk_app "$rat" s []

let sum a b = mk_app (etype a b) "$sum" [a; b]
let mul a b = mk_app (etype a b) "$product" [a; b]
let minus_one e = mk_app (get_type e) "$difference" [e; const "1"]
let plus_one e = mk_app (get_type e) "$sum" [e; const "1"]

let eeq a b = mk_app "$o" "$eq_num" [a; b]
let less a b = mk_app "$o" "$less" [a; b]
let lesseq a b = mk_app "$o" "$lesseq" [a; b]
let greater a b = mk_app "$o" "$greater" [a; b]
let greatereq a b = mk_app "$o" "$greatereq" [a; b]

let rec fadd_aux (c, x) = function
    | [] -> [(c, x)]
    | (c', y) :: r ->
            if equal x y then
                (Q.add c c', x) :: r
            else
                (c', y) :: (fadd_aux (c, x) r)

let fadd a b = List.fold_left (fun e c -> fadd_aux c e) a b
let fdiff a b = fadd a (List.map (fun (c, x) -> (Q.neg c, x)) b)
let fmul c a = List.map (fun (c', x) -> (Q.mul c c', x)) a

let normalize a b =
    let rec sanitize = function
        | [] -> []
        | (c, _) as a :: r -> if Q.equal Q.zero c then r else a :: (sanitize r)
    in
    let rec pop_const = function
        | [] -> (Q.zero, [])
        | (c, x) :: r ->
                if equal etrue x then
                    (Q.neg c), r
                else
                    let c', r' = pop_const r in
                    c', (c, x) :: r'
    in
    let coef e =
        if e = [] then
            Q.one
        else
            let k = Q.of_bigint (List.fold_left (fun k c -> if Q.is_real c then Z.lcm k (Q.den c) else k) Z.one e) in
            let aux = (fun g c -> Z.gcd g (Q.to_bigint (Q.mul c k))) in
            Q.of_bigint (List.fold_left aux (Q.to_bigint (Q.mul (List.hd e) k)) (List.tl e))
    in
    let f = fdiff a b in
    let c, e = pop_const f in
    let e = sanitize e in
    let k = coef (List.map fst e) in
    Q.div c k, (List.map (fun (c, x) -> (Q.div c k, x)) e)

let of_cexpr e = match e with
    | Eapp (s, [], _) when is_int e || is_rat e ->
            begin try
                Q.of_string s
            with Invalid_argument _ ->
                raise Exit
            end
    | _ -> raise NotaFormula

let rec of_nexpr = function
    | Eapp (v, [], _) as e ->
        begin try [of_cexpr e, etrue] with Exit -> [Q.one, e] end
    | Evar (v, _) as a when is_int a || is_rat a -> [Q.one, a]
    | Etau (_, ("$int"|"$rat"), _, _) as a -> [Q.one, a]
    | Eapp ("$sum", [a; b], _) -> fadd (of_nexpr a) (of_nexpr b)
    | Eapp ("$difference", [a; b], _) -> fdiff (of_nexpr a) (of_nexpr b)
    | Eapp ("$product", [Eapp (_, [], _) as e; a], _)
    | Eapp ("$product", [a; Eapp (_, [], _) as e], _) ->
            begin try
                fmul (of_cexpr e) (of_nexpr a)
            with Exit ->
                raise NotaFormula
            end
    | _ -> raise NotaFormula

let of_bexpr = function
    | Eapp (("$less"|"$lesseq"|"$greater"|"$greatereq"|"$eq_num") as s, [a; b], _ ) ->
            let a', b' = of_nexpr a, of_nexpr b in
            let c, e = normalize a' b' in
            (e, s, c)
    | _ -> raise NotaFormula

let to_nexpr = function
    | [] -> const "0"
    | (c, x) :: r -> List.fold_left (fun e (c', x') -> sum e (mul (const (Q.to_string c')) x')) (mul (const (Q.to_string c)) x) r

let to_bexpr (e, s, c) = mk_app "$o" s [to_nexpr e; const (Q.to_string c)]

let expr_norm e = try to_bexpr (of_bexpr e) with NotaFormula -> e

(* Nodes generated by the extension *)

let mk_node_const s c e g = (* e is a trivially false comparison of constants *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "const_" ^ s, [const (Q.to_string c)]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| |];
    }

let mk_node_eq a b e g = (* e : a = b *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "eq", [a; b]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [expr_norm (lesseq a b); expr_norm (greatereq a b)] |];
    }

let mk_node_neq a b e g = (* e : a != b *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "neq", [a; b]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [expr_norm (less a b)]; [expr_norm (greater a b)] |];
    }

let mk_node_tighten s x c e g =
    Node {
        nconc = [e];
        nrule = Ext ("arith", "tighten_" ^ s, [x; const c]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [mk_app "$o" s [x; const c]] |];
    }

let mk_node_var e1 e2 e g = (* e1 : v = expr, e2 : v {comp} const, e : expr {comp} const *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "var", [e1; e2]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [e1; e2] |];
    }

let mk_node_neg s a b e g = (* e : ~ a {s} b *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "neg_" ^ s, [a; b]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [mk_app "$o" (comp_neg s) [a; b] ] |];
    }

let mk_node_int_lt a b e g = (* e : a < b, => a <= b - 1 *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "int_lt", [a; b]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [expr_norm (lesseq a (minus_one b))] |];
    }

let mk_node_int_gt a b e g = (* e : a > b, => a >= b + 1 *)
    Node {
        nconc = [e];
        nrule = Ext ("arith", "int_gt", [a; b]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [expr_norm (greatereq a (plus_one b))] |];
    }

let mk_node_branch v e e' g =
    Node {
        nconc = [];
        nrule = Ext ("arith", "branch", [v; e; e']);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [e]; [e'] |];
    }

let mk_node_lin v e l g =
    Node {
        nconc = l;
        nrule = Ext ("arith", "lin", [expr_norm e]);
        nprio = Prop;
        ngoal = g;
        nbranches = [| [e] |];
    }

exception Internal_error
let nodes_of_tree s f t =
    let rec aux f t = match !t with
    | None -> raise Internal_error
    | Some S.Branch (v, k, c, c') ->
            let k = const (Z.to_string k) in
            let under = lesseq v k in
            let above = expr_norm (greatereq v (plus_one k)) in
            (f, mk_node_branch v under above) :: (aux under c) @ (aux above c')
    | Some S.Explanation (v, expr) ->
            let l = List.map snd expr in
            let relevant = snd (List.split (List.filter (fun (y, _) -> List.exists (fun x -> equal x y) l) t.bindings)) in
            let clin = mk_app "$o" "$eq_num" [v; to_nexpr expr] in

            [f, mk_node_lin clin relevant f;
             clin, mk_node_sim clin bounds comp]
    in
    aux f t

(* Helper around the simplex module *)
type simplex = {
    core : S.t;
    ignore : expr list;
    bindings : (expr * expr * expr option * expr option) list;
}

let simplex_empty = {
    core = S.empty;
    ignore = [];
    bindings = [];
}

let bounds_of_comp s c = match s with
    | "$lesseq" -> (Q.minus_inf, c)
    | "$greatereq" -> (c, Q.inf)
    | _ -> (Q.minus_inf, Q.inf)

let simplex_add t (e, s, c) = match e with
    | []  -> assert false
    | [(c', x)] ->
            let b = Q.div c (Q.abs c') in
            let (inf, upp) = bounds_of_comp s b in
            let (inf, upp) = if Q.sign c' <= -1 then (Q.neg upp, Q.neg inf) else (inf, upp) in
            let (_, def, low, high) = List.find (fun (y, _, _, _) -> equal x y) t.bindings in
            { t with core = S.add_bounds t.core (x, inf, upp);
                     bindings = add_bonding s }, []
    | _ ->
            let expr = to_nexpr e in
            let v = add_type (get_type expr) (newvar ()) in
            let e1 = eeq v expr in
            let e2 = mk_app "$o" s [v; const (Q.to_string c)] in
            { core = S.add_eq t.core (v, e);
              ignore = e1 :: t.ignore;
              bindings = (v, e1, None, None) :: t.bindings;
            }, [mk_node_var e1 e2]

let simplex_solve s e =
    let res = S.nsolve s.core is_int in
    match res with
    | S.Solution _ -> false, []
    | S.Unsatisfiable cert -> true, nodes_of_tree s e cert

(* Internal state *)
type state = {
    mutable solved : bool;
    stack : (expr * simplex * ((expr * (int -> Node.node_item)) list)) Stack.t;
}

let empty_state = {
    solved = false;
    stack = Stack.create ();
}

let st_solved st = st.solved <- true

let st_pop st =
    ignore (Stack.pop st.stack);
    st.solved <- false

let st_head st =
    try
        let _, r, _ = Stack.top st.stack in
        r
    with Stack.Empty -> simplex_empty

let st_push st x = Stack.push x st.stack

let st_is_head st e =
    try
        let e', _, _ = Stack.top st.stack in
        equal e e'
    with Stack.Empty -> false

(* Extension functions *)
exception Found of (int -> node_item)

let ignore_expr, add_expr, remove_formula, todo, add_todo =
    let st = empty_state in
    let is_new e =
        try Stack.iter (fun (e', _, l) ->
            if (List.exists (fun (e', _) -> equal e e') l) then raise Exit) st.stack;
        true
        with Exit -> false
    and ignore_expr e =
        try
            Stack.iter (fun (_, t, _) -> if List.exists (equal e) t.ignore then raise Exit) st.stack;
            false
        with Exit -> true
    in
    let add e = (* try and compute a solution *)
        if is_new e && not st.solved && not (ignore_expr e) then begin
            try
                let (f, s, c) = of_bexpr e in
                let t = st_head st in
                if f <> [] then begin
                    let t', res = simplex_add t (f, s, c) in
                    let b, res' = simplex_solve t' e in
                    let res'' = (List.map (fun x -> (e, x e)) res) @ res' in
                    st_push st (e, t', res'');
                    if b then st_solved st
                end
            with NotaFormula -> ()
        end
    and remove e = if st_is_head st e then st_pop st
    and add_todo e n = st_push st (e, (st_head st), [e, n])
    and todo e g =
        try
            Stack.iter (fun (e', _, l) -> try
                raise (Found (snd (List.find (fun (e', _) -> equal e e') l)))
            with Not_found -> ()) st.stack;
            raise Not_found
        with Found n -> n g
    in
    ignore_expr, add, remove, todo, add_todo

let const_node e = (* comparison of constants *)
    let (f, s, c) = of_bexpr e in
    assert (f = []);
    begin match s with
    | "$less" when Q.geq Q.zero c -> add_todo e (mk_node_const "lt" c e)
    | "$lesseq" when Q.gt Q.zero c -> add_todo e (mk_node_const "leq" c e)
    | "$greater" when Q.leq Q.zero c -> add_todo e (mk_node_const "gt" c e)
    | "$greatereq" when Q.lt Q.zero c -> add_todo e (mk_node_const "geq" c e)
    | _ -> ()
    end

let is_const e = try let (f, _, _) = of_bexpr e in f = [] with NotaFormula -> false

let add_formula e = match e with
    | _ when ignore_expr e -> ()
    | Enot (Eapp ("$eq_num", [a; b], _), _) ->
            add_todo e (mk_node_neq a b e)
    | Enot (Eapp (("$less"|"$lesseq"|"$greater"|"$greatereq") as s, [a; b], _), _) ->
            add_todo e (mk_node_neg s a b e)
    | _ when is_const e ->
            const_node e
    | Eapp ("$eq_num", [a; b], _) ->
            add_todo e (mk_node_eq a b e)
    | Eapp ("$less", [a; b], _) when is_int a && is_int b ->
            add_todo e (mk_node_int_lt a b e)
    | Eapp ("$greater", [a; b], _) when is_int a && is_int b ->
            add_todo e (mk_node_int_gt a b e)
    | _ ->
            try begin match (of_bexpr e) with
            | [(c', x)], ("$less"|"$lesseq"), c when is_int x && is_q (Q.div c c') ->
                    let c'' = Q.div c c' in
                    if Q.sign c' <= -1 then
                        add_todo e (mk_node_tighten "$greatereq" x (Q.to_string (ceil c'')) e)
                    else
                        add_todo e (mk_node_tighten "$lesseq" x (Q.to_string (floor c'')) e)
            | [(c', x)], ("$greater"|"$greatereq"), c when is_int x && is_q (Q.div c c') ->
                    let c'' = Q.div c c' in
                    if Q.sign c' <= -1 then
                        add_todo e (mk_node_tighten "$lesseq" x (Q.to_string (floor c'')) e)
                    else
                        add_todo e (mk_node_tighten "$greatereq" x (Q.to_string (ceil c'')) e)
            | _ -> add_expr e
            end with
            | NotaFormula -> ()

let newnodes e g _ = try [todo e g] with Not_found -> []

let make_inst term g = assert false

let to_llproof f p t = t.(0)

let declare_context_coq fmt = ()

let p_rule_coq fmt r = ()

let predef () = []
;;

Extension.register {
  Extension.name = "arith";
  Extension.newnodes = newnodes;
  Extension.make_inst = make_inst;
  Extension.add_formula = add_formula;
  Extension.remove_formula = remove_formula;
  Extension.preprocess = (fun x -> x);
  Extension.add_phrase = (fun _ -> ());
  Extension.postprocess = (fun x -> x);
  Extension.to_llproof = to_llproof;
  Extension.declare_context_coq = declare_context_coq;
  Extension.p_rule_coq = p_rule_coq;
  Extension.predef = predef;
};;

